version: "3"
services:
  pg:
    image: postgres:14
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=TEST-aWLIRsv8QHhxTFNqRb7EScj8erNSdDTYs0vpZ8jE6rwK
      - POSTGRES_USER=decidim
      - POSTGRES_DB=decidim_test
    ports:
      - 5432:5432
volumes:
  pg-data: {}
